version: '3.7'

services:

  django-seed:
    image: django-seed
    build: .
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    networks:
      - backend
      - default
    depends_on:
      - database

  database:
    image: mongo
    volumes:
      - mongodata:/data/db

  # broker:
  # worker:

volumes:
  mongodata:

networks:
  backend:
    name: backend
