version: '3.7'

services:

  # postgres database for kong state
  kong-database:
    image: postgres:9.6
    networks:
      - default
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong

  # kong database migration
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      - default
    environment:
      KONG_PG_HOST: kong-database

  # konga database prepare
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong@kong-database:5432/konga_db"
    networks:
      - default
    depends_on:
      - kong-database

  # kong main service
  kong:
    image: kong:latest
    networks:
      - default
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444

  # kong UI manager
  konga:
    image: pantsel/konga:next
    networks:
      - default
    environment:
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_DATABASE: konga_db
    ports:
      - 1337:1337

networks:
  default:
  backend:
    name: backend
  
