version: '3.7'

services:

  nginx:
    image: nginx:1.17.5-alpine
    ports:
      - 80:80
    volumes:
      - ./blog:/code/blog
      - ./wp:/code/wp
      - ./html:/code/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:5-fpm
    volumes:
      - ./blog:/code/blog
      - ./wp:/code/wp
      - ./html:/code/html
    networks:
      - default

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpressroot
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - default

networks:
  default:

  # wordpress-blog:
  #   depends_on:
  #     - mysql
  #   image: wordpress:latest
  #   volumes:
  #     - ./wp-content/themes:/var/www/html/wp-content/themes
  #     - ./wp-config.php:/var/www/html/wp-config.php
  #   ports:
  #     - 8001:80
