version: '3.7'

services:

  nginx:
    image: nginx:1.17.5-alpine
    volumes:
      - ./root:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  php:
    image: php:5-fpm
    volumes:
      - ./root:/code
    networks:
      - default

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpressroot
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - default

networks:
  default:
