# master compose

version: '3.7'

services:

  websocket:
    image: websocket
    build: .
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
    depends_on:
      - redis
    networks:
      - backend
      - default

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - default

networks:
  backend:
    name: backend
  default:
